// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  crpeSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Accueil',
    },
    {
      type: 'category',
      label: '🔬 Sciences et Technologie',
      collapsed: true,
      items: [
        'sciences/matiere-etats-changements',
        'sciences/melanges-solutions',
        'sciences/atomes-molecules-reactions',
        'sciences/energie-sources-conversions',
        'sciences/electricite',
        'sciences/mouvement-forces',
        'sciences/lumiere-optique',
        'sciences/son',
        'sciences/vivant-classification-biodiversite',
        'sciences/fonctions-nutrition',
        'sciences/reproduction-developpement',
        'sciences/ecosystemes-environnement',
        'sciences/corps-humain-sante',
        'sciences/terre-systeme-solaire',
        'sciences/objets-techniques-programmation',
      ],
    },
    {
      type: 'category',
      label: '🎨 Éducation Artistique',
      collapsed: true,
      items: [
        'arts/arts-plastiques-fondamentaux',
        'arts/arts-plastiques-oeuvres-2026',
        'arts/education-musicale-fondamentaux',
        'arts/education-musicale-oeuvres-2026',
        'arts/histoire-des-arts-2026',
      ],
    },
    {
      type: 'category',
      label: '⚽ EPS',
      collapsed: true,
      items: [
        'eps/eps-didactique-developpement',
        'eps/eps-apsa-champs-apprentissage',
      ],
    },
    {
      type: 'category',
      label: '🇬🇧 Anglais',
      collapsed: true,
      items: [
        'anglais/anglais-grammaire',
        'anglais/anglais-didactique',
        'anglais/anglais-vocabulaire-culture',
      ],
    },
    {
      type: 'category',
      label: '🇫🇷 Français',
      collapsed: true,
      items: [
        'francais/grammaire',
        'francais/lecture',
        'francais/expression-ecrite',
        'francais/expression-orale',
        'francais/culture-litteraire',
      ],
    },
    {
      type: 'category',
      label: '🔢 Mathématiques',
      collapsed: true,
      items: [
        'maths/nombres-entiers-decimaux',
        'maths/fractions-nombres-rationnels',
        'maths/nombres-relatifs',
        'maths/puissances-racines-carrees',
        'maths/calcul-litteral',
        'maths/geometrie-plane',
        'maths/geometrie-espace',
        'maths/grandeurs-mesures',
        'maths/durees-calculs',
        'maths/reperage',
        'maths/organisation-gestion-donnees',
        'maths/algorithmique-programmation',
      ],
    },
    {
      type: 'category',
      label: '📜 Histoire',
      collapsed: true,
      items: [
        'histoire/prehistoire',
        'histoire/premieres-civilisations',
        'histoire/grece-antique',
        'histoire/rome',
        'histoire/moyen-age-societe-feodale',
        'histoire/eglise-moyen-age',
        'histoire/grandes-decouvertes',
        'histoire/renaissance',
        'histoire/revolution-empire',
        'histoire/xixe-siecle',
        'histoire/guerres-mondiales',
        'histoire/monde-depuis-1945',
      ],
    },
    {
      type: 'category',
      label: '🌍 Géographie',
      collapsed: true,
      items: [
        'geographie/geo_lieux_habite',
        'geographie/geo_loger_travailler',
        'geographie/geo_consommer',
        'geographie/geo_urbanisation_mobilites',
        'geographie/geo_ressources',
        'geographie/geo_risques_climat',
        'geographie/geo_demographie_developpement',
        'geographie/geo_france_ue_mondialisation',
      ],
    },
    {
      type: 'category',
      label: '🏛️ EMC',
      collapsed: true,
      items: [
        'emc/emc_sensibilite',
        'emc/emc_droit_regle',
        'emc/emc_jugement',
        'emc/emc_engagement',
        'emc/emc_laicite',
        'emc/emc_egalite_discriminations',
      ],
    },
  ],
};

module.exports = sidebars;
