/**
 * sidebarsQuiz.js - Navigation pour la section Quiz
 * 
 * Structure identique aux fiches pour une navigation cohérente.
 * À placer à la racine du projet (à côté de sidebars.js)
 */

module.exports = {
  quizSidebar: [
    'intro',
    {
      type: 'category',
      label: '📝 Français',
      items: [
        { type: 'autogenerated', dirName: 'francais' },
      ],
    },
    {
      type: 'category',
      label: '🔢 Mathématiques',
      items: [
        { type: 'autogenerated', dirName: 'maths' },
      ],
    },
    {
      type: 'category',
      label: '📜 Histoire',
      items: [
        { type: 'autogenerated', dirName: 'histoire' },
      ],
    },
    {
      type: 'category',
      label: '🌍 Géographie',
      items: [
        { type: 'autogenerated', dirName: 'geographie' },
      ],
    },
    {
      type: 'category',
      label: '🌈 EMC',
      items: [
        { type: 'autogenerated', dirName: 'emc' },
      ],
    },
    {
      type: 'category',
      label: '🔬 Sciences',
      items: [
        { type: 'autogenerated', dirName: 'sciences' },
      ],
    },
    {
      type: 'category',
      label: '🎨 Arts',
      items: [
        { type: 'autogenerated', dirName: 'arts' },
      ],
    },
    {
      type: 'category',
      label: '⚽ EPS',
      items: [
        { type: 'autogenerated', dirName: 'eps' },
      ],
    },
    {
      type: 'category',
      label: '🇬🇧 Anglais',
      items: [
        { type: 'autogenerated', dirName: 'anglais' },
      ],
    },
  ],
};
